#!/bin/bash
#url=$1
url=https://www.youtube.com/watch?v=d8EecxeUqLU
tmpfn=tmp.wav
fn=song.wav

function download() {
    youtube-dl --extract-audio --audio-format wav -o $tmpfn $url
    [[ $? -eq 1 ]] && exit 1

    ffmpeg -i $tmpfn -y $fn
    [[ $? -eq 1 ]] && exit 1
}

function convert() {
    sox $fn $tmpfn rate 8k channels 1
    [[ $? -eq 1 ]] && exit 1 || mv $tmpfn $fn

    ffmpeg -i $fn -ab 128k -y $fn
}

download
convert
soxi $fn
